# Author: Cody Welsh
# License: GPL 3.0
# I suggest viewing https://github.com/phusion/baseimage-docker
# for more information about this image.

FROM phusion/baseimage:0.10.1
CMD ["/sbin/my_init"]



RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
